# Generated by Django 5.0 on 2024-01-09 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_steg", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="post",
            name="stegimage",
            field=models.ImageField(default="default.jpeg", upload_to="steg_image"),
        ),
        migrations.AddField(
            model_name="post",
            name="stegtext",
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="hiddentext",
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name="post",
            name="stegtype",
            field=models.CharField(max_length=20),
        ),
    ]
