# Generated by Django 5.0.1 on 2024-01-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_steg", "0003_alter_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="stegimage",
            field=models.ImageField(upload_to="steg_image"),
        ),
    ]
